import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..')
const read=f=>fs.readFileSync(path.join(root,f),'utf8')
test('admin: sessão assinada e APIs protegidas',()=>{const a=read('src/lib/admin-auth.ts');assert.match(a,/createHmac/);assert.match(a,/ADMIN_SESSION_SECRET/);for(const r of ['tenants','pedidos','pagamentos'])assert.match(read(`src/app/api/admin/${r}/route.ts`),/requireAdminApi|requireAdminSession|getAdminSession/)})
test('lojista: papéis, associação ativa e tenant selecionado controlam o acesso',()=>{const a=read('src/lib/tenant-auth.ts');for(const r of ['owner','manager','attendant','kitchen','motoboy','delivery'])assert.ok(a.includes(`'${r}'`));assert.match(a,/from\('usuarios_loja'\)/);assert.match(a,/\.eq\('user_id', user\.id\)\.eq\('ativo', true\)/);assert.match(a,/wd_active_tenant/);assert.match(a,/tenantStatus === 'active'/);assert.match(a,/if \(!auth\.user\) return 401/);assert.match(a,/if \(!auth\.tenantId\) return 403/)})
test('Loja A/B: consultas usam o tenant da sessão e nunca user.id',()=>{for(const f of ['src/app/api/pedidos/route.ts','src/app/api/clientes/route.ts','src/app/api/despesas/route.ts','src/app/api/mesas/route.ts','src/app/api/configuracoes/entregas/route.ts','src/app/api/usuarios-loja/route.ts']){const s=read(f);assert.match(s,/authenticatedTenant\(/,f);assert.match(s,/tenantId/,f);assert.doesNotMatch(s,/tenant_id\s*:\s*user(?:\.user)?\.id|\.eq\(['"]tenant_id['"],\s*user(?:\.user)?\.id\)/,f)}assert.match(read('src/app/api/auth/login/route.ts'),/cookies\.set\('wd_active_tenant'/)})
test('cliente: identidade e armazenamento ficam isolados por loja',()=>{const p=read('src/app/api/pedidos/public/route.ts');assert.match(p,/\.eq\('tenant_id', tenant\.id\)\.eq\('cliente_acesso_token_hash', hash\)/);assert.match(p,/hashAccessToken\(String\(cliente_access_token\)\)/);const c=read('src/components/checkout-flow.tsx');assert.match(c,/delivery_cliente_dados_\$\{tenantSlug \|\| tenantId\}/);assert.match(c,/delivery_carrinho_\$\{tenantSlug \|\| tenantId\}/)})
test('checkout: aniversário aceita oito dígitos, é opcional e validado no servidor',()=>{const c=read('src/components/checkout-flow.tsx');assert.match(c,/formatBirthdayInput\(e\.target\.value\)/);assert.match(c,/placeholder="DD\/MM\/AAAA"/);assert.match(c,/maxLength=\{10\}/);assert.match(c,/Pular esta etapa/);assert.match(c,/aniversario:'',cpf:''/);const p=read('src/app/api/pedidos/public/route.ts');assert.match(p,/const aniversarioIso = cliente_aniversario \? String\(cliente_aniversario\) : ''/);assert.match(p,/if \(aniversarioIso && !validIsoDate\(aniversarioIso\)\)/)})
test('pedido público: idempotência é obrigatória e vinculada à loja',()=>{const p=read('src/app/api/pedidos/public/route.ts');assert.match(p,/request\.headers\.get\('idempotency-key'\)/);assert.match(p,/String\(idempotencyKey\)\.length < 32/);assert.match(p,/hashAccessToken\(`\$\{tenant\.id\}:\$\{String\(idempotencyKey\)\}`\)/);assert.match(p,/rpc\('criar_pedido_atomico'/);const m=read('supabase/migrations/045_pedido_atomico_convites.sql');assert.match(m,/idempot/i);assert.match(m,/unique/i)})
test('PIX: UUID sozinho não autoriza leitura',()=>{const p=read('src/app/api/pedido-pix/route.ts');assert.match(p,/bearerToken\(request\)/);assert.match(p,/token\.length < 32/);assert.match(p,/cliente_acesso_token_hash/);assert.match(p,/tokenMatches\(token, pedido\.cliente_acesso_token_hash\)/);assert.match(p,/hashAccessToken\(token\) !== pedido\.cliente_acesso_token_hash/)})
test('avaliações: convite hash-only, expira e tem consumo único',()=>{const r=read('src/app/api/avaliacoes/public/route.ts');assert.match(r,/hashAccessToken\(String\(token\)\)/);assert.match(r,/\.eq\('avaliacao_token_hash', tokenHash\)/);assert.doesNotMatch(r,/\.eq\('avaliacao_token', token\)/);assert.match(r,/avaliacao_token_expires_at/);assert.match(r,/avaliacao_token_used_at/);assert.match(r,/\.is\('avaliacao_token_used_at', null\)/);assert.match(read('supabase/migrations/050_remove_plaintext_review_tokens.sql'),/drop column if exists avaliacao_token/)})
test('marquee contínuo: cópias idênticas e deslocamento sem emenda',()=>{const c=read('src/components/cardapio-cliente.tsx'),s=read('src/app/globals.css');assert.match(c,/wd-announcement-sequence[^]*renderTextos\('a', 12\)[^]*wd-announcement-sequence[^]*renderTextos\('b', 12\)/);assert.match(c,/aria-hidden="true"/);assert.match(s,/\.wd-announcement-track\s*\{[^}]*width:max-content/);assert.match(s,/\.wd-announcement-sequence\s*\{[^}]*flex-shrink:0/);assert.match(s,/@keyframes wd-marquee\s*\{\s*to\s*\{\s*transform:translate3d\(-50%,0,0\)/)})
