'use client'

import { useEffect, useMemo, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { ArrowLeftRight, BarChart3, CreditCard, FileText, Receipt, Truck, WalletCards } from 'lucide-react'
import { formatCurrency } from '@/lib/utils'

type Tab = 'overview'|'movements'|'cashflow'|'accounts'|'delivery'|'payments'|'reports'|'closing'
type Order = { id:string; created_at:string; valor_total:number; taxa_entrega:number; forma_pagamento:string; status:string }
type Expense = { id:string; nome:string; valor:number; dia_vencimento?:number|null; recorrencia?:string|null; created_at:string }
type StockMovement = { id:string; tipo:'entrada'|'saida'; quantidade:number; created_at:string; observacao?:string|null; insumos?:{nome:string;unidade:string;custo_unitario:number}|null }
type TenantFinance = { id:string; config:Record<string,unknown> }
const tabs = [
  ['overview','Visão geral',BarChart3],['movements','Entradas e saídas',ArrowLeftRight],['cashflow','Fluxo de caixa',WalletCards],['accounts','Contas a pagar/receber',Receipt],
  ['delivery','Taxas de entrega',Truck],['payments','Formas de pagamento',CreditCard],['reports','Relatórios',FileText],['closing','Fechamento de caixa',WalletCards],
] as const

export default function FinanceiroPage(){
  const supabase=useMemo(()=>createClient(),[]); const[tab,setTab]=useState<Tab>('overview'); const[orders,setOrders]=useState<Order[]>([]); const[expenses,setExpenses]=useState<Expense[]>([]); const[movements,setMovements]=useState<StockMovement[]>([]); const[tenant,setTenant]=useState<TenantFinance|null>(null); const[loading,setLoading]=useState(true)
  useEffect(()=>{(async()=>{try{const response=await fetch('/api/financeiro',{cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(body.error);setOrders(body.orders||[]);setExpenses(body.expenses||[]);setMovements(body.movements||[]);setTenant(body.tenant)}finally{setLoading(false)}})()},[])
  const validOrders=orders.filter(o=>o.status!=='cancelado');const realizedOrders=validOrders.filter(o=>o.status==='entregue');const pendingOrders=validOrders.filter(o=>o.status!=='entregue');const revenue=realizedOrders.reduce((s,o)=>s+Number(o.valor_total||0),0);const pendingRevenue=pendingOrders.reduce((s,o)=>s+Number(o.valor_total||0),0);const expenseTotal=expenses.reduce((s,e)=>s+Number(e.valor||0),0);const deliveryTotal=validOrders.reduce((s,o)=>s+Number(o.taxa_entrega||0),0);const balance=revenue-expenseTotal
  const days=useMemo(()=>{const result=new Map<string,number>();realizedOrders.forEach(o=>{const key=new Date(o.created_at).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'});result.set(key,(result.get(key)||0)+Number(o.valor_total||0))});return [...result].slice(0,7).reverse()},[realizedOrders]);const max=Math.max(1,...days.map(([,v])=>v))
  if(loading)return <div className="hint p-8">Carregando dados financeiros…</div>
  return <div className="space-y-5"><header><div className="eyebrow mb-2">Financeiro</div><h1 className="text-3xl font-semibold">Gestão financeira</h1><p className="hint mt-1">Pedidos, despesas, estoque e configurações reunidos em um só lugar.</p></header>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`glass-soft min-h-24 rounded-2xl p-4 text-left transition ${tab===id?'ring-2 ring-green-500':''}`}><Icon size={18}/><span className="block text-sm font-semibold mt-2">{label}</span></button>)}</div>
    {tab==='overview'&&<p className="hint text-sm">Receita pendente: {formatCurrency(pendingRevenue)} em pedidos não cancelados e ainda não entregues.</p>}
    {tab==='overview'&&<><Metrics revenue={revenue} expenses={expenseTotal} balance={balance} orders={orders.length}/><section className="glass p-5"><h2 className="font-semibold mb-4">Vendas recentes por dia</h2>{days.length?<div className="h-48 flex items-end gap-3">{days.map(([day,value])=><div key={day} className="flex-1 text-center"><div className="bg-green-500 rounded-t-lg" style={{height:`${Math.max(8,value/max*150)}px`}} title={formatCurrency(value)}/><span className="text-xs hint">{day}</span></div>)}</div>:<Empty text="Ainda não há pedidos para formar o gráfico."/>}</section></>}
    {tab==='movements'&&<Movements rows={movements}/>} {tab==='cashflow'&&<CashFlow orders={validOrders} expenses={expenses}/>} {tab==='accounts'&&<Accounts orders={validOrders} expenses={expenses}/>} {tab==='delivery'&&<Delivery orders={validOrders} total={deliveryTotal}/>} {tab==='payments'&&<Payments tenant={tenant} onSaved={setTenant}/>} {tab==='reports'&&<Reports orders={realizedOrders} revenue={revenue} expenses={expenseTotal}/>} {tab==='closing'&&<Closing orders={validOrders} expenses={expenses}/>} </div>
}
function Metrics({revenue,expenses,balance,orders}:any){return <div className="grid md:grid-cols-4 gap-3">{[['Receita realizada (entregues)',revenue],['Despesas cadastradas',expenses],['Saldo realizado',balance],['Pedidos consultados',orders]].map(([l,v],i)=><div key={String(l)} className="glass p-4"><p className="hint text-xs">{l}</p><p className="text-xl font-bold mt-1">{i===3?String(v):formatCurrency(Number(v))}</p></div>)}</div>}
const Empty=({text}:{text:string})=><p className="hint text-sm py-8 text-center">{text}</p>
function Movements({rows}:{rows:any[]}){return <section className="glass p-5"><h2 className="font-semibold mb-3">Movimentações de insumos</h2>{rows.length?rows.map(r=><div key={r.id} className="border-b py-3 flex justify-between"><div><b>{r.insumos?.nome||'Insumo'}</b><p className="hint text-xs">{new Date(r.created_at).toLocaleString('pt-BR')} · {r.observacao||'Sem observação'}</p></div><span className={r.tipo==='entrada'?'text-green-700':'text-red-700'}>{r.tipo==='entrada'?'+':'-'}{Number(r.quantidade)} {r.insumos?.unidade}</span></div>):<Empty text="Nenhuma entrada ou saída de insumo registrada."/>}</section>}
function CashFlow({orders,expenses}:{orders:Order[];expenses:any[]}){const rows=[...orders.map(o=>({date:o.created_at,label:`Pedido #${o.id.slice(0,8)}`,value:Number(o.valor_total),kind:'entrada'})),...expenses.map(e=>({date:e.created_at,label:e.nome,value:-Number(e.valor),kind:'saída'}))].sort((a,b)=>+new Date(b.date)-+new Date(a.date));return <section className="glass p-5"><h2 className="font-semibold mb-3">Fluxo registrado</h2>{rows.length?rows.slice(0,100).map((r,i)=><div key={`${r.kind}-${i}`} className="flex justify-between border-b py-3"><span>{r.label}<small className="block hint">{new Date(r.date).toLocaleDateString('pt-BR')}</small></span><b className={r.value>=0?'text-green-700':'text-red-700'}>{formatCurrency(r.value)}</b></div>):<Empty text="Sem lançamentos para exibir."/>}</section>}
function Accounts({orders,expenses}:{orders:Order[];expenses:any[]}){return <div className="grid md:grid-cols-2 gap-4"><section className="glass p-5"><h2 className="font-semibold">Contas a pagar</h2>{expenses.length?expenses.map(e=><p key={e.id} className="border-b py-3 flex justify-between"><span>{e.nome}<small className="block hint">dia {e.dia_vencimento||'—'} · {e.recorrencia}</small></span><b>{formatCurrency(Number(e.valor))}</b></p>):<Empty text="Nenhuma despesa cadastrada."/>}</section><section className="glass p-5"><h2 className="font-semibold">Valores de pedidos</h2><p className="hint text-xs mb-2">Pedidos registrados; conciliação bancária não é automática.</p>{orders.length?orders.slice(0,30).map(o=><p key={o.id} className="border-b py-3 flex justify-between"><span>#{o.id.slice(0,8)}<small className="block hint">{o.status}</small></span><b>{formatCurrency(Number(o.valor_total))}</b></p>):<Empty text="Nenhum pedido registrado."/>}</section></div>}
function Delivery({orders,total}:{orders:Order[];total:number}){const charged=orders.filter(o=>Number(o.taxa_entrega)>0);return <section className="glass p-5"><h2 className="font-semibold">Taxas de entrega</h2><p className="text-2xl font-bold my-3">{formatCurrency(total)}</p>{charged.length?charged.slice(0,50).map(o=><p key={o.id} className="flex justify-between border-b py-2"><span>Pedido #{o.id.slice(0,8)}</span><b>{formatCurrency(Number(o.taxa_entrega))}</b></p>):<Empty text="Nenhuma taxa cobrada nos pedidos consultados."/>}</section>}
function Payments({tenant,onSaved}:{tenant:any;onSaved:(v:any)=>void}){const initial=tenant?.config?.formas_pagamento_aceitas||{};const[values,setValues]=useState<Record<string,boolean>>(initial);async function save(){const response=await fetch('/api/financeiro',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({formas:values})});const body=await response.json();if(response.ok){onSaved({...tenant,config:body.config});alert('Formas de pagamento salvas.')}else alert(body.error||'Não foi possível salvar.')}return <section className="glass p-5"><h2 className="font-semibold mb-3">Formas aceitas no cardápio</h2>{[['dinheiro','Dinheiro'],['pix','Pix'],['cartao_credito','Cartão de crédito'],['cartao_debito','Cartão de débito']].map(([id,label])=><label key={id} className="flex justify-between border-b py-3"><span>{label}</span><input type="checkbox" checked={!!values[id]} onChange={()=>setValues(v=>({...v,[id]:!v[id]}))}/></label>)}<button onClick={save} className="btn-primary mt-4">Salvar</button></section>}
function Reports({orders,revenue,expenses}:any){const byPayment=orders.reduce((a:any,o:Order)=>{a[o.forma_pagamento||'não informado']=(a[o.forma_pagamento||'não informado']||0)+Number(o.valor_total);return a},{});return <section className="glass p-5"><h2 className="font-semibold mb-3">Resumo do período disponível</h2><Metrics revenue={revenue} expenses={expenses} balance={revenue-expenses} orders={orders.length}/><div className="mt-4">{Object.entries(byPayment).map(([k,v])=><p key={k} className="flex justify-between border-b py-2"><span>{k.replaceAll('_',' ')}</span><b>{formatCurrency(Number(v))}</b></p>)}</div></section>}
function Closing({orders,expenses}:{orders:Order[];expenses:any[]}){const today=new Date().toDateString();const dayOrders=orders.filter(o=>new Date(o.created_at).toDateString()===today&&o.status!=='cancelado');const entries=dayOrders.reduce((s,o)=>s+Number(o.valor_total),0);const out=expenses.filter(e=>new Date(e.created_at).toDateString()===today).reduce((s,e)=>s+Number(e.valor),0);return <section className="glass p-5"><h2 className="font-semibold">Fechamento de hoje</h2><p className="hint text-xs mb-4">Consolidação dos registros do sistema; confira com caixa e extratos.</p><Metrics revenue={entries} expenses={out} balance={entries-out} orders={dayOrders.length}/></section>}
