/* eslint-disable @typescript-eslint/no-require-imports */
// Verificacao read-only da migration 047; nunca executa DDL/DML.
const { query } = require('./lib/supabase-management')
const assert=(ok,msg)=>{if(!ok)throw new Error(msg)}
async function main(){
 const policies=await query(`select schemaname,tablename,policyname,roles,cmd,coalesce(qual,'') qual,coalesce(with_check,'') with_check from pg_policies where schemaname in ('public','storage') order by 1,2,3`)
 const tables=await query(`select n.nspname schema_name,c.relname table_name,c.relrowsecurity,c.relforcerowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('r','p')`)
 const grants=await query(`select table_schema,table_name,grantee,privilege_type from information_schema.role_table_grants where table_schema='public' and grantee in ('PUBLIC','anon','authenticated')`)
 const columns=await query(`select table_schema,table_name,column_name,grantee,privilege_type from information_schema.column_privileges where table_schema='public' and grantee in ('PUBLIC','anon','authenticated')`)
 const functions=await query(`select p.oid::regprocedure::text signature,pg_get_functiondef(p.oid) definition,has_function_privilege('anon',p.oid,'EXECUTE') anon_execute,has_function_privilege('authenticated',p.oid,'EXECUTE') authenticated_execute,has_function_privilege('service_role',p.oid,'EXECUTE') service_role_execute,coalesce(bool_or(a.grantee=0 and a.privilege_type='EXECUTE'),false) public_execute from pg_proc p join pg_namespace n on n.oid=p.pronamespace left join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a on true where n.nspname='public' and p.prosecdef=true group by p.oid order by 1`)
 const triggers=await query(`select n.nspname schema_name,c.relname table_name,t.tgname,pg_get_triggerdef(t.oid,true) definition from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where not t.tgisinternal and n.nspname='public'`)
 const buckets=await query(`select id,public from storage.buckets where id in ('produtos','cardapio-assets','complementos','logos')`)
 const required=['tenants','usuarios_loja','categorias','produtos','complementos','clientes','pedidos','pedido_itens','mensalidades','pix_pagamentos','auditoria','avaliacoes','categorias_complementos','categorias_produtos','variantes','produto_complementos','pedido_complementos']
 for(const name of required){assert(tables.find(t=>t.table_name===name)?.relrowsecurity,`RLS ausente: ${name}`);assert(policies.some(p=>p.schemaname==='public'&&p.tablename===name),`Sem policy: ${name}`)}
 assert(!policies.some(p=>/ranieryrick4@gmail\.com/i.test(`${p.qual} ${p.with_check}`)),'Policy com email fixo')
 assert(!policies.some(p=>/^Admin full access/i.test(p.policyname)),'Policy admin aberta')
 const anonMutation=grants.filter(g=>g.grantee==='anon'&&['INSERT','UPDATE','DELETE'].includes(g.privilege_type));assert(!anonMutation.length,`anon mutacao: ${JSON.stringify(anonMutation)}`)
 const publicSafe={tenants:['id','nome','slug','logo_url','cor_principal','telefone','cidade','estado','bairro','endereco','numero','complemento','tipo_estabelecimento','categoria','logo_path','banner_url','banner_path','latitude','longitude','status'],categorias:['id','tenant_id','nome','ordem','ativo'],produtos:['id','tenant_id','categoria_id','categoria_produto_id','nome','descricao','imagem_url','preco','ativo','tempo_preparo_min','preco_riscado','etiquetas'],variantes:['id','produto_id','nome','preco_adicional'],complementos:['id','tenant_id','categoria_id','nome','preco','ativo','ordem','imagem_url','imagem_path','descricao','etiqueta1','etiqueta2','etiqueta3','qtd_max'],produto_complementos:['produto_id','complemento_id'],categorias_produtos:['id','tenant_id','nome','ordem','ativo'],categorias_complementos:['id','tenant_id','nome','ordem','ativo','obrigatorio','max_selecoes','qtd_minima','qtd_maxima','max_um_de_cada','imagem_url'],avaliacoes:['tenant_id','nota','comentario','resposta_admin','created_at']}
 for(const [table,safe] of Object.entries(publicSafe)){assert(!grants.some(g=>g.table_name===table&&g.grantee==='anon'&&g.privilege_type==='SELECT'),`anon SELECT integral: ${table}`);const exposed=columns.filter(g=>g.table_name===table&&g.grantee==='anon'&&g.privilege_type==='SELECT').map(g=>g.column_name);assert(exposed.length,`anon sem columns: ${table}`);assert(exposed.every(c=>safe.includes(c)),`coluna anon sensivel em ${table}: ${exposed.filter(c=>!safe.includes(c))}`)}
 for(const table of ['usuarios_loja','mensalidades','pix_pagamentos','auditoria'])assert(!grants.some(g=>g.grantee==='authenticated'&&g.table_name===table&&['UPDATE','DELETE'].includes(g.privilege_type)),`mutacao sensivel: ${table}`)
 assert(!grants.some(g=>g.grantee==='authenticated'&&g.table_name==='auditoria'&&g.privilege_type==='INSERT'),'auditoria INSERT direto')
 const expectedPolicies=['Catalogo publico ve listas de complementos','Catalogo publico ve avaliacoes aprovadas','Categorias de produtos publicas','Membros ativos leem categorias de produtos','Gestores administram categorias de produtos'];for(const name of expectedPolicies)assert(policies.filter(p=>p.policyname===name).length===1,`Policy ausente/duplicada: ${name}`)
 for(const rel of ['produto_complementos','complemento_categorias','pedido_complementos','produto_insumos']){if(!tables.some(t=>t.table_name===rel))continue;const text=policies.filter(p=>p.tablename===rel).map(p=>`${p.qual} ${p.with_check}`).join(' ');assert(/tenant_id/.test(text)&&/owner/.test(text)&&/manager/.test(text),`Relacao sem validacao cruzada/RBAC: ${rel}`)}
 const storage=policies.find(p=>p.schemaname==='storage'&&p.policyname==='Membros gerenciam imagens do tenant');const st=`${storage?.qual} ${storage?.with_check}`;assert(/has_active_tenant_role/.test(st)&&/owner/.test(st)&&/manager/.test(st)&&/storage\.foldername/.test(st),'Storage sem RBAC/pasta');for(const b of ['produtos','cardapio-assets','complementos','logos']){assert(st.includes(b),`Storage sem ${b}`);assert(buckets.some(x=>x.id===b&&x.public===true),`Bucket incompativel ${b}`)}
 assert(!grants.some(g=>g.table_name==='tenants'&&g.grantee==='authenticated'&&g.privilege_type==='SELECT'),'authenticated SELECT integral tenants');const tenantSensitive=['cpf','cnpj','data_nascimento','email','telefone','nome_responsavel'];const tenantSelect=columns.filter(g=>g.table_name==='tenants'&&g.grantee==='authenticated'&&g.privilege_type==='SELECT').map(g=>g.column_name);assert(!tenantSensitive.some(c=>tenantSelect.includes(c)), 'PII tenants exposta: '+tenantSensitive.filter(c=>tenantSelect.includes(c)).join(','));
 for(const table of ['mensalidades','pix_pagamentos','auditoria']){const text=policies.filter(p=>p.tablename===table).map(p=>`${p.qual} ${p.with_check}`).join(' ');assert(/has_active_tenant_role/.test(text)&&/owner/.test(text)&&/manager/.test(text),`RBAC financeiro/auditoria fraco: ${table}`)}
 const kitchenSensitive=['cliente_nome','cliente_whatsapp','endereco_entrega','numero_entrega','complemento_entrega','bairro_entrega','troco_para','observacoes'];const pedidoSelect=columns.filter(g=>g.table_name==='pedidos'&&g.grantee==='authenticated'&&g.privilege_type==='SELECT').map(g=>g.column_name);assert(!grants.some(g=>g.table_name==='pedidos'&&g.grantee==='authenticated'&&g.privilege_type==='SELECT'),'authenticated SELECT integral pedidos');assert(!kitchenSensitive.some(c=>pedidoSelect.includes(c)), 'PII pedidos exposta: '+kitchenSensitive.filter(c=>pedidoSelect.includes(c)).join(','));
 for(const table of ['pedido_itens','enderecos_entrega'])assert(!policies.some(p=>p.tablename===table&&/^Admin full|visiveis ao tenant/i.test(p.policyname)),`Policy extra antiga: ${table}`)
 assert(policies.filter(p=>p.schemaname==='storage'&&p.tablename==='objects'&&/(produtos|cardapio-assets|complementos|logos)/.test(`${p.qual} ${p.with_check}`)).length===2,'Policies storage extras nos buckets gerenciados');assert(!grants.some(g=>g.table_name==='pedidos'&&g.grantee==='authenticated'&&g.privilege_type==='UPDATE'),'UPDATE integral pedidos');const pedidoUpdate=columns.filter(g=>g.table_name==='pedidos'&&g.grantee==='authenticated'&&g.privilege_type==='UPDATE').map(g=>g.column_name).sort();assert(JSON.stringify(pedidoUpdate)===JSON.stringify(['data_atualizacao','motoboy_id','status']),'Columns UPDATE pedidos inseguras');
 const fn=signature=>functions.find(f=>f.signature===signature);
 assert(triggers.some(t=>t.table_name==='pedidos'&&t.tgname==='trg_validar_atualizacao_operacional_pedido'&&/validar_atualizacao_operacional_pedido/.test(t.definition)),'Trigger operacional ausente');
 assert(!grants.some(g=>g.table_name==='saas_config'&&['anon','PUBLIC'].includes(g.grantee)&&g.privilege_type==='SELECT'),'saas_config publico');assert(!functions.some(f=>f.anon_execute||f.public_execute),'SECURITY DEFINER para anon/PUBLIC');assert(fn('registrar_auditoria(uuid,uuid,text,text,uuid,jsonb,jsonb)')?.service_role_execute&&!fn('registrar_auditoria(uuid,uuid,text,text,uuid,jsonb,jsonb)')?.authenticated_execute,'ACL auditoria');assert(fn('sortear_campanha(uuid)')?.authenticated_execute&&/has_active_tenant_role[\s\S]*owner[\s\S]*manager/.test(fn('sortear_campanha(uuid)').definition),'ACL/RBAC sorteio');assert(fn('aceitar_convite_loja(text)')?.authenticated_execute,'convite quebrado');for(const signature of ['consume_api_rate_limit(text,integer,integer)','criar_pedido_atomico(uuid,text,text,jsonb,jsonb,jsonb)','verificar_trial_tenant(uuid)','incrementar_usos_cupom(uuid,text)'])assert(fn(signature)?.service_role_execute,`service_role ausente ${signature}`);const allowedAuthenticated=['is_active_tenant_member(uuid)','has_active_tenant_role(uuid,text[])','aceitar_convite_loja(text)','sortear_campanha(uuid)'];assert(!functions.some(f=>f.authenticated_execute&&!allowedAuthenticated.includes(f.signature)), 'SECURITY DEFINER authenticated fora da allowlist')
 console.log(JSON.stringify({result:'ok',policies_checked:policies.length,tables_checked:required.length,functions_checked:functions.length,buckets_checked:buckets.length},null,2))
}
main().catch(e=>{console.error(`RLS 047 verification failed: ${e.message}`);process.exit(1)})