'use client'
import { useEffect, useMemo, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { Plus, Users, Copy } from 'lucide-react'
import { formatCurrency } from '@/lib/utils'
async function getActiveTenant(){const r=await fetch('/api/auth/session',{cache:'no-store'});const b=await r.json();if(!r.ok||!b.tenant?.id)throw new Error('Loja ativa não encontrada');return String(b.tenant.id)}

export default function EmbaixadoresPage(){
 const db=createClient(); const [lista,setLista]=useState<any[]>([]); const [indicacoes,setIndicacoes]=useState<any[]>([]); const [form,setForm]=useState({nome:'',email:'',telefone:'',codigo:'',tipo_comissao:'percentual',comissao_percentual:'0',comissao_fixa:'0'}); const [msg,setMsg]=useState('')
 async function load(){const tid=await getActiveTenant(); const [a,b]=await Promise.all([db.from('embaixadores').select('*').eq('tenant_id',tid).order('created_at',{ascending:false}),db.from('indicacoes_embaixador').select('*,embaixadores(nome)').eq('tenant_id',tid).order('created_at',{ascending:false})]);setLista(a.data||[]);setIndicacoes(b.data||[])}
 useEffect(()=>{load()},[])
 async function criar(e:React.FormEvent){e.preventDefault();const tid=await getActiveTenant();const codigo=(form.codigo||form.nome).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]/g,'').toUpperCase();const {error}=await db.from('embaixadores').insert({...form,codigo,tenant_id:tid,comissao_percentual:Number(form.comissao_percentual),comissao_fixa:Number(form.comissao_fixa)});setMsg(error?.message||'Embaixador cadastrado.');if(!error){setForm({nome:'',email:'',telefone:'',codigo:'',tipo_comissao:'percentual',comissao_percentual:'0',comissao_fixa:'0'});load()}}
 async function status(id:string,status_comissao:string){await db.from('indicacoes_embaixador').update({status_comissao,pago_em:status_comissao==='paga'?new Date().toISOString():null}).eq('id',id);load()}
 const total=useMemo(()=>indicacoes.filter(i=>i.status_comissao!=='cancelada').reduce((s,i)=>s+Number(i.valor_comissao||0),0),[indicacoes])
 return <div><header className="bg-white border rounded-2xl p-5 mb-4"><p className="text-xs text-gray-500 flex gap-1"><Users size={13}/> Crescimento</p><h1 className="text-3xl font-bold">Embaixadores</h1><p className="text-sm text-gray-500">Codigos de indicacao, conversoes, comissoes e pagamentos.</p></header><div className="grid md:grid-cols-3 gap-3 mb-4"><Card l="Embaixadores" v={lista.length}/><Card l="Indicacoes" v={indicacoes.length}/><Card l="Comissoes" v={formatCurrency(total)}/></div>
 <form onSubmit={criar} className="bg-white border rounded-2xl p-4 grid md:grid-cols-4 gap-3 mb-4"><input required className="form-input" placeholder="Nome" value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/><input className="form-input" placeholder="E-mail" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className="form-input" placeholder="Codigo (automatico)" value={form.codigo} onChange={e=>setForm({...form,codigo:e.target.value})}/><select className="form-input" value={form.tipo_comissao} onChange={e=>setForm({...form,tipo_comissao:e.target.value})}><option value="percentual">Percentual</option><option value="fixa">Fixa</option></select><input type="number" step=".01" className="form-input" placeholder="Percentual" value={form.comissao_percentual} onChange={e=>setForm({...form,comissao_percentual:e.target.value})}/><input type="number" step=".01" className="form-input" placeholder="Valor fixo" value={form.comissao_fixa} onChange={e=>setForm({...form,comissao_fixa:e.target.value})}/><button className="btn-primary"><Plus size={15}/>Cadastrar</button>{msg&&<span className="text-sm text-gray-500 self-center">{msg}</span>}</form>
 <section className="bg-white border rounded-2xl overflow-auto mb-4"><table className="w-full text-sm"><thead><tr className="bg-gray-50"><th className="p-3 text-left">Nome</th><th>Codigo/link</th><th>Comissao</th><th>Status</th></tr></thead><tbody>{lista.map(a=><tr className="border-t" key={a.id}><td className="p-3 font-medium">{a.nome}</td><td><button className="inline-flex gap-1" onClick={()=>navigator.clipboard.writeText(`${location.origin}/registro?ref=${a.codigo}`)}>{a.codigo}<Copy size={13}/></button></td><td>{a.tipo_comissao==='fixa'?formatCurrency(a.comissao_fixa):`${a.comissao_percentual}%`}</td><td>{a.ativo?'Ativo':'Inativo'}</td></tr>)}</tbody></table></section>
 <section className="bg-white border rounded-2xl overflow-auto"><h2 className="font-semibold p-4">Extrato de indicacoes</h2><table className="w-full text-sm"><thead><tr className="bg-gray-50"><th className="p-3 text-left">Embaixador</th><th>Indicado</th><th>Conversao</th><th>Comissao</th><th>Pagamento</th></tr></thead><tbody>{indicacoes.map(i=><tr className="border-t" key={i.id}><td className="p-3">{i.embaixadores?.nome}</td><td>{i.nome_indicado||i.email_indicado||'Tenant vinculado'}</td><td>{i.status}</td><td>{formatCurrency(i.valor_comissao)}</td><td><select className="form-input" value={i.status_comissao} onChange={e=>status(i.id,e.target.value)}><option value="pendente">Pendente</option><option value="aprovada">Aprovada</option><option value="paga">Paga</option><option value="cancelada">Cancelada</option></select></td></tr>)}</tbody></table></section></div>
}
function Card({l,v}:{l:string,v:any}){return <div className="bg-white border rounded-2xl p-4"><div className="text-xs text-gray-500">{l}</div><div className="text-2xl font-bold">{v}</div></div>}
