-- Sprint 5/6: logistica, avaliacoes seguras, embaixadores e sorteios.
-- Migration idempotente e nao destrutiva.

ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS avaliacao_token UUID DEFAULT gen_random_uuid();
CREATE UNIQUE INDEX IF NOT EXISTS idx_pedidos_avaliacao_token ON pedidos(avaliacao_token);
CREATE UNIQUE INDEX IF NOT EXISTS idx_avaliacoes_pedido_unico ON avaliacoes(pedido_id) WHERE pedido_id IS NOT NULL;

CREATE OR REPLACE FUNCTION incrementar_usos_cupom(p_tenant_id UUID, p_codigo TEXT)
RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  UPDATE cupons SET usos_atuais = COALESCE(usos_atuais, 0) + 1
  WHERE tenant_id = p_tenant_id AND upper(codigo) = upper(p_codigo);
$$;

CREATE TABLE IF NOT EXISTS embaixadores (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  email TEXT,
  telefone TEXT,
  codigo TEXT NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT true,
  tipo_comissao TEXT NOT NULL DEFAULT 'percentual' CHECK (tipo_comissao IN ('percentual','fixa')),
  comissao_percentual NUMERIC(7,2) NOT NULL DEFAULT 0,
  comissao_fixa NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, codigo)
);
CREATE INDEX IF NOT EXISTS idx_embaixadores_tenant ON embaixadores(tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_embaixadores_codigo_global ON embaixadores(upper(codigo));
ALTER TABLE embaixadores ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Embaixadores do proprio tenant" ON embaixadores;
CREATE POLICY "Embaixadores do proprio tenant" ON embaixadores FOR ALL USING (tenant_id = auth.uid()) WITH CHECK (tenant_id = auth.uid());

CREATE TABLE IF NOT EXISTS indicacoes_embaixador (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  embaixador_id UUID NOT NULL REFERENCES embaixadores(id) ON DELETE RESTRICT,
  tenant_indicado_id UUID REFERENCES tenants(id) ON DELETE SET NULL,
  nome_indicado TEXT,
  email_indicado TEXT,
  status TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente','convertida','cancelada')),
  valor_base NUMERIC(12,2) NOT NULL DEFAULT 0,
  valor_comissao NUMERIC(12,2) NOT NULL DEFAULT 0,
  status_comissao TEXT NOT NULL DEFAULT 'pendente' CHECK (status_comissao IN ('pendente','aprovada','paga','cancelada')),
  pago_em TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, tenant_indicado_id)
);
CREATE INDEX IF NOT EXISTS idx_indicacoes_embaixador ON indicacoes_embaixador(tenant_id, embaixador_id);
ALTER TABLE indicacoes_embaixador ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Indicacoes do proprio tenant" ON indicacoes_embaixador;
CREATE POLICY "Indicacoes do proprio tenant" ON indicacoes_embaixador FOR ALL USING (tenant_id = auth.uid()) WITH CHECK (tenant_id = auth.uid());

CREATE TABLE IF NOT EXISTS campanhas_sorteio (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  descricao TEXT,
  inicio_em TIMESTAMPTZ NOT NULL,
  fim_em TIMESTAMPTZ NOT NULL,
  valor_minimo_pedido NUMERIC(12,2) NOT NULL DEFAULT 0,
  cupons_por_pedido INTEGER NOT NULL DEFAULT 1 CHECK (cupons_por_pedido > 0),
  ativo BOOLEAN NOT NULL DEFAULT true,
  sorteado_em TIMESTAMPTZ,
  vencedor_cupom_id UUID,
  seed_auditoria UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (fim_em > inicio_em)
);
CREATE INDEX IF NOT EXISTS idx_campanhas_sorteio_tenant ON campanhas_sorteio(tenant_id, ativo);
ALTER TABLE campanhas_sorteio ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Campanhas do proprio tenant" ON campanhas_sorteio;
CREATE POLICY "Campanhas do proprio tenant" ON campanhas_sorteio FOR ALL USING (tenant_id = auth.uid()) WITH CHECK (tenant_id = auth.uid());

CREATE TABLE IF NOT EXISTS cupons_sorteio (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  campanha_id UUID NOT NULL REFERENCES campanhas_sorteio(id) ON DELETE CASCADE,
  pedido_id UUID NOT NULL REFERENCES pedidos(id) ON DELETE CASCADE,
  numero BIGINT GENERATED BY DEFAULT AS IDENTITY,
  cliente_nome TEXT,
  cliente_whatsapp TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (campanha_id, pedido_id, numero)
);
CREATE INDEX IF NOT EXISTS idx_cupons_sorteio_consulta ON cupons_sorteio(tenant_id, cliente_whatsapp);
ALTER TABLE cupons_sorteio ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Cupons do proprio tenant" ON cupons_sorteio;
CREATE POLICY "Cupons do proprio tenant" ON cupons_sorteio FOR ALL USING (tenant_id = auth.uid()) WITH CHECK (tenant_id = auth.uid());

ALTER TABLE campanhas_sorteio DROP CONSTRAINT IF EXISTS campanhas_sorteio_vencedor_cupom_id_fkey;
ALTER TABLE campanhas_sorteio ADD CONSTRAINT campanhas_sorteio_vencedor_cupom_id_fkey FOREIGN KEY (vencedor_cupom_id) REFERENCES cupons_sorteio(id) ON DELETE SET NULL;

CREATE OR REPLACE FUNCTION gerar_cupons_sorteio_pedido() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE c RECORD; i INTEGER;
BEGIN
  FOR c IN SELECT * FROM campanhas_sorteio WHERE tenant_id=NEW.tenant_id AND ativo AND now() BETWEEN inicio_em AND fim_em AND COALESCE(NEW.valor_total,0) >= valor_minimo_pedido AND sorteado_em IS NULL LOOP
    FOR i IN 1..c.cupons_por_pedido LOOP
      INSERT INTO cupons_sorteio(tenant_id,campanha_id,pedido_id,cliente_nome,cliente_whatsapp)
      VALUES(NEW.tenant_id,c.id,NEW.id,NEW.cliente_nome,regexp_replace(COALESCE(NEW.cliente_whatsapp,''),'\D','','g'));
    END LOOP;
  END LOOP;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_gerar_cupons_sorteio ON pedidos;
CREATE TRIGGER trg_gerar_cupons_sorteio AFTER INSERT ON pedidos FOR EACH ROW EXECUTE FUNCTION gerar_cupons_sorteio_pedido();

CREATE OR REPLACE FUNCTION aplicar_comissao_motoboy() RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE v_comissao NUMERIC(10,2);
BEGIN
  IF NEW.status='entregue' AND OLD.status IS DISTINCT FROM 'entregue' AND NEW.motoboy_id IS NOT NULL AND NEW.motoboy_comissao IS NULL THEN
    SELECT CASE WHEN tipo_comissao='fixa' THEN comissao_fixa ELSE COALESCE(NEW.taxa_entrega,0)*COALESCE(comissao_percent,0)/100 END INTO v_comissao FROM motoboys WHERE id=NEW.motoboy_id AND tenant_id=NEW.tenant_id;
    IF v_comissao IS NOT NULL THEN NEW.motoboy_comissao := round(v_comissao,2); UPDATE motoboys SET total_entregas=COALESCE(total_entregas,0)+1,total_ganho=COALESCE(total_ganho,0)+round(v_comissao,2) WHERE id=NEW.motoboy_id; END IF;
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_aplicar_comissao_motoboy ON pedidos;
CREATE TRIGGER trg_aplicar_comissao_motoboy BEFORE UPDATE OF status ON pedidos
FOR EACH ROW EXECUTE FUNCTION aplicar_comissao_motoboy();

CREATE OR REPLACE FUNCTION sortear_campanha(p_campanha_id UUID) RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_tenant UUID; v_cupom UUID; v_seed UUID;
BEGIN
  SELECT tenant_id INTO v_tenant FROM campanhas_sorteio WHERE id=p_campanha_id FOR UPDATE;
  IF v_tenant IS NULL OR v_tenant <> auth.uid() THEN RAISE EXCEPTION 'campanha nao autorizada'; END IF;
  IF EXISTS (SELECT 1 FROM campanhas_sorteio WHERE id=p_campanha_id AND sorteado_em IS NOT NULL) THEN RAISE EXCEPTION 'campanha ja sorteada'; END IF;
  v_seed := gen_random_uuid();
  SELECT id INTO v_cupom FROM cupons_sorteio WHERE campanha_id=p_campanha_id ORDER BY md5(id::text || v_seed::text) LIMIT 1;
  IF v_cupom IS NULL THEN RAISE EXCEPTION 'campanha sem cupons'; END IF;
  UPDATE campanhas_sorteio SET vencedor_cupom_id=v_cupom,sorteado_em=now(),seed_auditoria=v_seed,ativo=false WHERE id=p_campanha_id;
  RETURN v_cupom;
END $$;
