/* eslint-disable @typescript-eslint/no-require-imports */
const fs=require('node:fs'),path=require('node:path');const {query}=require('../lib/supabase-management')
async function main(){const data={format:'we-delivery-rls-047-v4',captured_at:new Date().toISOString(),
relations:await query(`select n.nspname schema_name,c.relname relation_name,c.relkind,c.relrowsecurity,c.relforcerowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','storage') and c.relkind in ('r','p','S') order by 1,2`),
policies:await query(`select * from pg_policies where schemaname in ('public','storage') order by 1,2,3`),
table_grants:await query(`select table_schema,table_name,grantee,privilege_type from information_schema.role_table_grants where table_schema in ('public','storage') order by 1,2,3,4`),
column_grants:await query(`select table_schema,table_name,column_name,grantee,privilege_type from information_schema.column_privileges where table_schema in ('public','storage') order by 1,2,3,4,5`),
functions:await query(`select n.nspname schema_name,p.proname,pg_get_function_identity_arguments(p.oid) identity_arguments,p.oid::regprocedure::text signature,pg_get_functiondef(p.oid) definition from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' order by 2,3`),
function_grants:await query(`select n.nspname schema_name,p.proname,pg_get_function_identity_arguments(p.oid) identity_arguments,case when a.grantee=0 then 'PUBLIC' else pg_get_userbyid(a.grantee) end grantee,a.privilege_type from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where n.nspname='public' order by 2,3,4`),
schema_grants:await query(`select n.nspname schema_name,case when a.grantee=0 then 'PUBLIC' else pg_get_userbyid(a.grantee) end grantee,a.privilege_type from pg_namespace n cross join lateral aclexplode(coalesce(n.nspacl,acldefault('n',n.nspowner))) a where n.nspname in ('public','storage') order by 1,2,3`),
sequence_grants:await query(`select n.nspname schema_name,c.relname sequence_name,case when a.grantee=0 then 'PUBLIC' else pg_get_userbyid(a.grantee) end grantee,a.privilege_type from pg_class c join pg_namespace n on n.oid=c.relnamespace cross join lateral aclexplode(coalesce(c.relacl,acldefault('S',c.relowner))) a where n.nspname='public' and c.relkind='S' order by 2,3,4`),
triggers:await query(`select n.nspname schema_name,c.relname table_name,t.tgname,pg_get_triggerdef(t.oid,true) definition from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where not t.tgisinternal and n.nspname in ('public','storage') order by 1,2,3`),
buckets:await query(`select id,name,public,file_size_limit,allowed_mime_types from storage.buckets order by id`)};const dir=path.resolve('artifacts','rls-047');fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,`snapshot-${Date.now()}.json`);fs.writeFileSync(file,JSON.stringify(data,null,2),{flag:'wx'});console.log(file)}main().catch(e=>{console.error(`Snapshot failed: ${e.message}`);process.exit(1)})